### ISSUE TITLE
How to input the data

### ISSUE THREAD

**Issue by island-jie** [ArtificialSnow/closest-points-on-sphere#1]
Dear author, I want to use your code,but I can not input the correct data? Can you give the correct data input format?
Thank you very much.

**Comment by ArtificialSnow** [comment]
Hello,

Here is an example input:

5
yhseggbb 18.88652677101787 90.62671414861234
nhkopvmn -32.70724235597533 56.16884308792075
qcwnjmwq -8.25937498830639 116.2394076058705
bicmbmih -42.27291948210425 151.8237744853426
htvrbrur 71.30729253192621 -161.26537325875137
5
fjyhzask -65.05038318982695 84.97430994722845
ppnxnjrx -49.84505697596655 145.78308590313873
rrucrhwe -76.55501800599792 18.992724123494526
ldhbjvtl 16.082781867513134 -3.244062136949367
ovflweww 51.45317016824032 68.66389268629834
0


The first number is the number of points to be entered.
Then follows each point [name of point] [latitude of point] [longitude
of point].

Here is an image explaining:[image: Screenshot 2021-06-07 222955.png]

Kind regards,
Peter

**Comment by ArtificialSnow** [comment]
OK, I get the point. Thank you for you reply.
Best wishes.
LIN Jie


On 6/7/2021 18:34，Peter ***@***.***> wrote：
Hello,


Here is an example input:

5
yhseggbb 18.88652677101787 90.62671414861234
nhkopvmn -32.70724235597533 56.16884308792075
qcwnjmwq -8.25937498830639 116.2394076058705
bicmbmih -42.27291948210425 151.8237744853426
htvrbrur 71.30729253192621 -161.26537325875137
5
fjyhzask -65.05038318982695 84.97430994722845
ppnxnjrx -49.84505697596655 145.78308590313873
rrucrhwe -76.55501800599792 18.992724123494526
ldhbjvtl 16.082781867513134 -3.244062136949367
ovflweww 51.45317016824032 68.66389268629834
0


The first number is the number of points to be entered.
Then follows each point [name of point] [latitude of point] [longitude of point].

Here is an image explaining:


Kind regards,
Peter


On Thu, 3 Jun 2021 at 20:57, island-jie ***@***.***> wrote:


Dear author, I want to use your code,but I can not input the correct data? Can you give the correct data input format?
Thank you very much.

**Comment by ArtificialSnow** [comment]
No problem :)

Feel free to ask anymore questions if you have any

Kind regards,
Peter
